version: '3.7'

services:
  mysql:
    container_name: local.cs101.database
    image: mysql/mysql-server:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: computer_science
    ports:
      - '3306:3306'
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    platform: linux/amd64

